const Countries=["Select Country" 
    ,"United Arab Emirates"
    ,"Argentina"
    ,"Austria"
    ,"Australia"
    ,"Belgium"
    ,"Bulgaria"
    ,"Brazil"
    ,"Canada"
    ,"Switzerland"
    ,"China"
    ,"Colombia"
    ,"Cuba"
    ,"Czechia"
    ,"Germany"
    ,"Egypt"
    ,"France"
    ,"United Kingdom"
    ,"Greece"
    ,"Hong Kong"
    ,"Hungary"
    ,"Indonesia"
    ,"Ireland"
    ,"Israel"
    ,"India"
    ,"Italy"
    ,"Japan"
    ,"the Republic of Korea"
    ,"Lithuania"
    ,"Latvia"
    ,"Morocco"
    ,"Mexico"
    ,"Malaysia"
    ,"Nigeria"
    ,"Netherlands"
    ,"Norway"
    ,"New Zealand"
    ,"Philippines"
    ,"Poland"
    ,"Portugal"
    ,"Romania"
    ,"Serbia"
    ,"Russian Federation"
    ,"Saudi Arabia"
    ,"Sweden"
    ,"Singapore"
    ,"Slovenia"
    ,"Slovakia"
    ,"Thailand"
    ,"Türkiye"
    ,"Taiwan"
    ,"Ukraine"
    ,"United States of America"
    ,"Venezuela"
    ,"South Africa"];

 export default Countries;